# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-02 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=250)),
                ('AAPL_Open', models.FloatField(default=0.0)),
                ('AAPL_High', models.FloatField(default=0.0)),
                ('AAPL_Low', models.FloatField(default=0.0)),
                ('AAPL_Close', models.FloatField(default=0.0)),
                ('AAPL_Volumne', models.FloatField(default=0.0)),
                ('AAPL_Adjusted', models.FloatField(default=0.0)),
                ('dn', models.FloatField(default=0.0)),
                ('mavg', models.FloatField(default=0.0)),
                ('up', models.FloatField(default=0.0)),
                ('direction', models.CharField(max_length=250)),
            ],
        ),
    ]
