# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-15 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('passwd', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='sales',
        ),
    ]
