# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-05 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash10', '0003_userdbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='userreports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportname', models.CharField(max_length=250)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash10.user')),
            ],
        ),
    ]
