# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-08 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash10', '0005_userdashboards_userdatamodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatamodels',
            name='databasename',
            field=models.CharField(default='mysql', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdatamodels',
            name='databasetype',
            field=models.CharField(default='oracle', max_length=250),
            preserve_default=False,
        ),
    ]
